USE [master]
GO
/****** Object:  Database [CodeTestSGCIS]    Script Date: 9/12/2020 10:14:12 PM ******/
CREATE DATABASE [CodeTestSGCIS]
 CONTAINMENT = NONE
GO
ALTER DATABASE [CodeTestSGCIS] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodeTestSGCIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CodeTestSGCIS] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET ANSI_NULLS ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET ANSI_PADDING ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET ARITHABORT ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [CodeTestSGCIS] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [CodeTestSGCIS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CodeTestSGCIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CodeTestSGCIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET RECOVERY FULL 
GO
ALTER DATABASE [CodeTestSGCIS] SET  MULTI_USER 
GO
ALTER DATABASE [CodeTestSGCIS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CodeTestSGCIS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CodeTestSGCIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CodeTestSGCIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CodeTestSGCIS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CodeTestSGCIS] SET QUERY_STORE = OFF
GO
USE [CodeTestSGCIS]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [CodeTestSGCIS]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 9/12/2020 10:14:12 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[IdPerson] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](200) NOT NULL,
	[Age] [int] NOT NULL,
	[IdTypePerson] [int] NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[IdPerson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TypePerson]    Script Date: 9/12/2020 10:14:13 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TypePerson](
	[IdTypePerson] [int] NOT NULL,
	[TypePersonDescription] [varchar](200) NOT NULL,
 CONSTRAINT [PK_TypePerson] PRIMARY KEY CLUSTERED 
(
	[IdTypePerson] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Person]  WITH CHECK ADD  CONSTRAINT [FK_Person_PersonType] FOREIGN KEY([IdTypePerson])
REFERENCES [dbo].[TypePerson] ([IdTypePerson])
GO
ALTER TABLE [dbo].[Person] CHECK CONSTRAINT [FK_Person_PersonType]
GO
USE [master]
GO
ALTER DATABASE [CodeTestSGCIS] SET  READ_WRITE 
GO

SET IDENTITY_INSERT [dbo].[Usuario] ON 

INSERT [dbo].[TypePerson] ([IdTypePerson], [TypePersonDescription]) VALUES (1, N'Teacher')
INSERT [dbo].[TypePerson] ([IdTypePerson], [TypePersonDescription]) VALUES (2, N'Student')

SET IDENTITY_INSERT [dbo].[Usuario] OFF